name: sync

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  close-fork-pulls:
    runs-on: ubuntu-latest

    steps:
     - run: |
         git clone \
           --depth 1  \
           --filter=blob:none \
           --sparse \
           https://github.com/cdnjs-test/cdnjs.git
