name: sync

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  close-fork-pulls:
    runs-on: ubuntu-latest

    steps:
     - run: |
         git clone \
           --depth 1  \
           --filter=blob:none \
           --sparse \
           https://github.com/cdnjs-test/cdnjs.git

     - run: |
         cd cdnjs
         date > generated.txt
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         git commit -m "generated"

     - name: Push changes
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: test
         directory: cdnjs
